local map = vim.keymap.set

map("i", "<C-h>", "<Left>", { desc = "Cursor left" })
map("i", "<C-j>", "<Down>", { desc = "Cursor down" })
map("i", "<C-k>", "<Up>", { desc = "Cursor up" })
map("i", "<C-l>", "<Right>", { desc = "Cursor right" })
map("i", "jk", "<Esc>", { desc = "Exit insert mode" })

map("n", ";", ":", { desc = "Command mode" })
map("n", "<C-s>", "<cmd>w<CR>", { desc = "Save file" })

map("n", "<leader>fm", function()
	require("conform").format({ stop_after_first = true, lsp_fallback = true })
end, { desc = "Format buffer" })

map("n", "<leader>xx", "<cmd>Trouble<cr>", { desc = "Toggle trouble" })

map("n", "<leader>e", "<cmd>NvimTreeToggle<cr>", { desc = "Toggle file tree" })
map("n", "<leader>o", "<cmd>Oil<cr>", { desc = "Open oil explorer" })
map("n", "<leader>x", "<cmd>bd<cr>", { desc = "Close buffer" })

map("n", "<Tab>", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "<S-Tab>", "<cmd>bprev<cr>", { desc = "Prev buffer" })
map("n", "<C-d>", "<C-d>zz", { desc = "Scroll down and center" })
map("n", "<C-u>", "<C-u>zz", { desc = "Scroll up and center" })

map("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
map("n", "<C-j>", "<C-w>j", { desc = "Move to bottom window" })
map("n", "<C-k>", "<C-w>k", { desc = "Move to top window" })
map("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })

map("n", "<C-Left>", "5<C-w><", { desc = "Decrease window width" })
map("n", "<C-Right>", "5<C-w>>", { desc = "Increase window width" })
map("n", "<C-Up>", "5<C-w>+", { desc = "Increase window height" })
map("n", "<C-Down>", "5<C-w>-", { desc = "Decrease window height" })

local Terminal = require("toggleterm.terminal").Terminal
local lazygit_term = Terminal:new({ cmd = "lazygit", direction = "float", hidden = true })
local float_term = Terminal:new({ direction = "float", hidden = true })
local vert_term = Terminal:new({ direction = "vertical", hidden = true })
local horiz_term = Terminal:new({ direction = "horizontal", size = 15, hidden = true })

map("n", "<leader>lg", function()
	lazygit_term:toggle()
end, { desc = "Toggle lazygit" })
map("n", "<A-i>", function()
	float_term:toggle()
end, { desc = "Toggle floating terminal" })
map("n", "<A-v>", function()
	vert_term:toggle()
end, { desc = "Toggle vertical terminal" })
map("n", "<A-h>", function()
	horiz_term:toggle()
end, { desc = "Toggle horizontal terminal" })
map("t", "<A-i>", function()
	float_term:toggle()
end, { desc = "Toggle floating terminal" })
map("t", "<A-v>", function()
	vert_term:toggle()
end, { desc = "Toggle vertical terminal" })
map("t", "<A-h>", function()
	horiz_term:toggle()
end, { desc = "Toggle horizontal terminal" })

local dap = require("dap")
local dapui = require("dapui")
map("n", "<F5>", function()
	dap.continue()
end, { desc = "Debug continue" })
map("n", "<F10>", function()
	dap.step_over()
end, { desc = "Debug step over" })
map("n", "<F11>", function()
	dap.step_into()
end, { desc = "Debug step into" })
map("n", "<F12>", function()
	dap.step_out()
end, { desc = "Debug step out" })
map("n", "<leader>b", function()
	dap.toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
map("n", "<leader>B", function()
	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Set conditional breakpoint" })
map("n", "<leader>lp", function()
	dap.set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "Set log point" })
map("n", "<leader>dr", function()
	dap.repl.open()
end, { desc = "Open debug REPL" })
map("n", "<leader>dl", function()
	dap.run_last()
end, { desc = "Run last debug config" })
map({ "n", "v" }, "<leader>dh", function()
	dapui.eval()
end, { desc = "Evaluate expression" })
