local function repo(src, opts)
    return vim.tbl_extend("force", { src = src }, opts or {})
end

return {
    repo("https://github.com/nvim-tree/nvim-web-devicons"),
    repo("https://github.com/nvim-tree/nvim-tree.lua"),
    repo("https://github.com/nvim-treesitter/nvim-treesitter"),
    repo("https://github.com/neovim/nvim-lspconfig"),
    repo("https://github.com/folke/which-key.nvim"),
    repo("https://github.com/folke/trouble.nvim"),
    repo("https://github.com/chentoast/marks.nvim"),
    repo("https://github.com/nvim-telescope/telescope.nvim"),
    repo("https://github.com/nvim-lua/plenary.nvim"),
    repo("https://github.com/blazkowolf/gruber-darker.nvim"),
    repo("https://github.com/windwp/nvim-autopairs"),
    repo("https://github.com/lewis6991/gitsigns.nvim"),
    repo("https://github.com/saghen/blink.lib"),
    repo("https://github.com/saghen/blink.cmp"),
    repo("https://github.com/onsails/lspkind.nvim"),
    repo("https://github.com/lukas-reineke/indent-blankline.nvim"),
    repo("https://github.com/akinsho/bufferline.nvim"),
    repo("https://github.com/nvim-lualine/lualine.nvim"),
    repo("https://github.com/akinsho/toggleterm.nvim"),
    repo("https://github.com/mfussenegger/nvim-dap"),
    repo("https://github.com/rcarriga/nvim-dap-ui"),
    repo("https://github.com/nvim-neotest/nvim-nio"),
    repo("https://github.com/rachartier/tiny-glimmer.nvim"),
    repo("https://github.com/williamboman/mason.nvim"),
    repo("https://github.com/stevearc/conform.nvim"),
    repo("https://github.com/stevearc/oil.nvim"),
    repo("https://github.com/0x00-ketsu/autosave.nvim"),
    repo("https://github.com/rafamadriz/friendly-snippets"),
    repo("https://github.com/MeanderingProgrammer/render-markdown.nvim"),
    repo("https://github.com/folke/zen-mode.nvim"),
    repo("https://github.com/tpope/vim-dadbod"),
    repo("https://github.com/kristijanhusak/vim-dadbod-ui"),
    repo("https://github.com/kristijanhusak/vim-dadbod-completion"),
    repo("https://github.com/jtprogru/pack-ui.nvim"),
}
